name: Daily Lottery Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'  # 1 AM Eastern (5 AM UTC)

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci

      - name: Run scripts to update data
        run: |
          node generate.js
          node updateIndex.js

      - name: Commit and Push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add index.html lottery.json
          git commit -m "📅 Daily auto update" || echo "No changes to commit"
          git push
